config/routes.rb
NautsRails::Application.routes.draw do

    devise_for :admin_users, ActiveAdmin::Devise.config

    get "pages/terms"
    get "pages/welcome"
    get "pages/landing"
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
    resources :users
    resources :articles do
        resources :comments
    end
      resources :tags

  root :to => 'articles#index'
  ActiveAdmin.routes(self)

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :userarticles
    has_many :users, through: :userarticles

    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    geocoded_by :geo_address
    after_validation :geocode

    def geo_address
        coded_address = []
        coded_address.push self.address
        coded_address.push self.city
        coded_address.push self.zipcode
        coded_address.join(" ")
    end


    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

    def user_list
        self.users.collect do |user|
            user.email
        end.join(", ")
    end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    include ArticlesHelper

    def index
        @articles = Article.all
        @comments = Comment.all
    end

    def show
        @articles = Article.all
        @comments = Comment.all
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @articles = Article.all
        @comments = Comment.all
        @article = Article.new

    end

    def create
        @articles = Article.all
        @comments = Comment.all
        @article = Article.new(article_params)
        if @article.save
            flash.notice = "You've succesfully created the Article"
            @article.users.push(current_user)
            redirect_to @article
        else
            render new_article_path
        end
    end

    def edit
        @articles = Article.all
        @comments = Comment.all
        @article = Article.find(params[:id])
    end

    def update
        @articles = Article.all
        @comments = Comment.all
        @article = Article.find(params[:id])
            if (@article.users.exists?(email: current_user.email) != true) || (@article.users.length >= @article.players)
                    @article.users.push(current_user)
            end
        @article.update(article_params)
        flash.notice = "You've succesfully updated the Article"
        redirect_to @article
    end

    def destroy
        @articles = Article.all
        @comments = Comment.all
        @article = Article.find(params[:id])
        @article.tags = []
        @article.users = []
        @article.destroy
        flash.notice = "Article Destroyed"
        redirect_to articles_path(@articles)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper

    def article_params
        params.require(:article).permit(:title, :body, :rating, :address, :zipcode, :city, :state, :sport, :players, :latitude, :longitude, :location, :tag_list, :image, :geo_address, :player_names, :user, :user_list, :month, :time, :day, :setting )
    end


end

app/views/articles/_comment.html.erb
<div>
  <p class="comment"><%= comment.body %></p>
  <p class="comment-by">Comment by <%= comment.author_name %></p>
  <p class="comment-post">Posted <%= comment.article.created_at %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
    <ul>

        <% @article.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>

    <% if @article.users.length < 1 %>
            <p class="hideforplayer"><%= f.text_field :player_names, :value => current_user.email, :required => true %></p>
    <% end %>

    <div class="article-field">
        <div class="labler"><%= f.label :title %></div>
        <div class="fielder"><%= f.text_field :title, :placeholder => "Full court game", :required => true %></div>
    </div>

    <div class="article-field">
        <div class="labler"><%= f.label :body %></div>
        <div class="fielder"><%= f.text_area :body, :placeholder => "Looking for players to play on one of the most beautiful...", :required => true %></div>
    </div>

    <div class="setting-sport article-field">
        <div class="article-field">
            <div class="labler"><%= f.label :setting %></div>
            <div class="fielder"><%= f.text_field :setting, :placeholder => "ex: outdoors, indoors, park", :required => true %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :sport %></div>
            <div class="fielder"><%= f.select :sport, [['Basketball','basketball'],['Football','Football'],['Soccer','soccer'],['Baseball','baseball']], :required => true %></div>
        </div>

    </div>

    <div class="location-players">
        <div class="article-field">
            <div class="labler"><%= f.label :location %></div>
            <div class="fielder"><%= f.text_field :location, :placeholder => "ex: ruckers park", :required => true %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :players %></div>
            <div class="fielder"><%= f.number_field :players, :placeholder => "10", :required => true %></div>
        </div>
    </div>

    <div class="article-field">
        <div class="labler"><%= f.label :address %></div>
        <div class="fielder"><%= f.text_field :address, :placeholder => "W 155th street & 8th Ave...", :required => true %></div>
    </div>

    <div class="addresser">
        <div class="article-field">
            <div class="labler"><%= f.label :city %></div>
            <div class="fielder"><%= f.text_field :city, :placeholder => "new york", :required => true %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :state %></div>
            <div class="fielder"><%= f.text_field :state, :placeholder => "NY", :required => true %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :zipcode %></div>
            <div class="fielder"><%= f.number_field :zipcode, :placeholder => "10039, 10201" %></div>
        </div>
    </div>

    <div class="date-time">
        <div class="article-field">
            <div class="labler"><%= f.label :month %></div>
            <div class="fielder"><%= f.text_field :month, :placeholder => "january, february", :required => true %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :day %></div>
            <div class="fielder"><%= f.number_field :day, :placeholder => "1..29" %></div>
        </div>

        <div class="article-field">
            <div class="labler"><%= f.label :time %></div>
            <div class="fielder"><%= f.text_field :time, :placeholder => "6:30 pm", :required => true %></div>
        </div>
    </div>

    <div class="article-field">
        <div class="labler"><%= f.label :tag_list %> </div>
        <div class="fielder"><%= f.text_field :tag_list, :placeholder => "3v3, 4v4, full court..." %></div>
    </div>
    <p><%= f.submit id: "submitter" %></p>


<% end %>

app/views/articles/edit.html.erb
<div class="headpart"><h1>Edit game info</h1></div>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<div class="view-holder">
    <div class="now-viewing view">
        Now displaying
    </div>

    <div class="dropdown view">
        <span>All Sports</span>
        <div class="dropdown-content">
            <p><a href="../tags/1">all sports</a></p>
            <p><a href="../tags/1">basketball</a></p>
            <p><a href="../tags/2">football</a></p>
            <p><a href="../tags/3">soccer</a></p>
            <p><a href="../tags/4">baseball</a></p>
        </div>
    </div>
    <div class="end-viewing view">
        games
    </div>
</div>


<div class="rightsign">
    <% if user_signed_in? %>
    <p class="right-user">
        <%= link_to current_user.email.split('@')[0], current_user %> <span class="loggerout"><%= link_to "Logout", destroy_user_session_path %></span>
    </p>
    <%= link_to "Start A Sports Game", new_article_path, class: "new_article" %>
    <% else %>
    <p class="right-user"><%= link_to "Login/Sign-up", new_user_session_path %></p>
    <%= link_to 'login to start a game', '/users/sign_in', method: :get, class: "new_article" %>
    <% end %>
</div>

<div class="gmapper">
    <div id="map" style=' height: 350px;'></div>
</div>


<div id= "articles-holder">
    <% @articles.each do |article| %>
        <div class="all_articles">
            <div class="general-data">
                <h2 class="art-title"><%= link_to article.title.length >= 20 ? article.title.first(20) + "..." : article.title, article_path(article), 'data-no-turbolink' => true %></h2>
                <p class="article-p"> <span class="talic">Setting:</span> <%= article.setting %> <br>
                 <span class="talic">Location</span>: <%= article.location %></p>
                <p class="joined_body"><%= article.body.length >= 60 ? article.body.first(60) + "..." : article.body  %></p>
            </div>
            <div class="game-date">
                <p class="month"><%= article.month.to_s.first(3) %></p>
                <h2 class="day"><%= article.day.to_i.floor %></h2>
                <p class="time"><%=  article.time %></p>
            </div>
            <div class="players"></div>
                <p class="joined_players"><%=  article.players - article.users.length %> spots left out of <%= article.players%> </p>
                <p class = "postedby">posted by: </span>
                <% if article.users.length >= 1 %>
                    <span class=posted> <%= link_to article.player_names, '/users/1' %> </span>
                <% end %>
            </p>
        </div>
    <% end %>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    var markers = handler.addMarkers([

        <% @articles.each do |article| %>
            { lat: <%= article.latitude %>, lng: <%= article.longitude %>,
                infowindow: "<%= article.title %>"
            },
        <% end %>

    ]);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
});
</script>

app/views/articles/new.html.erb
<div class="headpart"><h1>Start a new pickup game</h1></div>


<%= render partial: 'form' %>

app/views/articles/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>


<div class="view-holder">

    <ul id="article-control">
        <li><%= link_to '< back', articles_path, 'data-no-turbolink' => true, id: "back-article"%></li>
        <% if user_signed_in? %>
        <% if  (@article.users.exists? )%>
        <% if (@article.player_names == current_user.email) %>
        <li><%= link_to 'delete', article_path(@article), id: "delete-article",  method: :delete, data: {confirm: "Really delete the article?"} %></li>
        <li><%= link_to 'edit', edit_article_path(@article), id: "edit-article" %></li>
        <% end %>
        <% end %>
        <% end %>
    </ul>
</div>

<div class="rightsign">
    <% if user_signed_in? %>
    <p class="right-user">
        <%= link_to current_user.email.split('@')[0], current_user %> <span class="loggerout"><%= link_to "Logout", destroy_user_session_path %></span>
    </p>
    <%= link_to "Start A Sports Game", new_article_path, class: "new_article" %>
    <% else %>
    <p class="right-user"><%= link_to "Login/Sign-up", new_user_session_path %></p>
    <%= link_to 'login to start a game', '/users/sign_in', method: :get, class: "new_article" %>
    <% end %>
</div>

<div class="game-info">


    <div class="gmapper">
        <div id="map" style=' height: 350px;'></div>
    </div>


<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>




<div class="article-game-info">
    <div class="game-date">
        <p class="month"><%= @article.month.to_s.first(3) %></p>
        <h2 class="day"><%= @article.day.to_i.floor %></h2>
        <p class="time"><%=  @article.time %></p>
    </div>
    <div class=game-data>
    <div id="h1-title"><h1><%= @article.title %></h1></div>
    <% if @article.users != [] %>
    <p class="postauthor"><span class="talic">posted by: </span> <%= @article.player_names %> on <%= @article.created_at.strftime("%b %d, %Y") %> </p>
    <% end %>

    <p><span class="talic"> sport: </span><%= @article.sport %> </p>

    <p><span class="talic">description:</span> <br>
        <%= @article.body %> </p>
    <p>
        <span class="talic"> Setting: </span><%= @article.setting %>  <br>
        <span class="talic"> Location: </span><%= @article.location %>  <br>
        <span class="talic"> Address: </span><%= @article.address%> <%= @article.city %> <%= @article.state %> <%= @article.zipcode %>
    </p>

    <div class="players-list">
        <ul>
            <li>    <span class="talic"> players joined: </span> </li>
            <% @article.users.each do |users|  %>
            <li><%= link_to users.email, users %></li>
            <% end %>
        </ul>
        <%= @article.players - @article.users.length %> spots left out of <%= @article.players %>


    </div>

    <% if user_signed_in? %>
        <%= form_for @article do |f| %>
            <% if @article.users.length < 1 %>
                    <p class="hideforplayer"><%= f.text_field :player_names, :value => current_user.email, :required => true %></p>
            <% end %>
        <p class="hideforplayer"><%= f.label :title %> <%= f.text_field :title %></p>
        <p class="join-party"> <%= f.submit "join game"%></p>
        <% end %>

    <% else %>
        <p class="logininplease">
            please <span><%= link_to 'login', '/users/sign_in', method: :get  %></span> to join this game
        </p>
    <% end %>

    </div>
    </div>
</div><!--gameinfo div  -->


<div class="comments-area">
<h3>Comments (<%=@article.comments.size %>)</h3>
<div id="commeter"><%= render partial: 'articles/comment', collection: @article.comments %></div>

    <% if user_signed_in? %>
    <div id="comments_form">
      <%= render partial: 'comments/form' %>
    </div>

    <% else %>
    <div id="comments-login">
        <p class="logininplease">
            please <span><%= link_to 'login', '/users/sign_in', method: :get  %></span> to post a message
        </p>
    </div>
    <% end %>
</div>



<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @article.latitude %>,
      "lng": <%= @article.longitude %>,
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});

</script>