config/routes.rb
NautsRails::Application.routes.draw do

    devise_for :admin_users, ActiveAdmin::Devise.config

    get "pages/terms"
    get "pages/welcome"
    get "pages/landing"
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
    resources :users
    resources :articles do
        resources :comments
    end
      resources :tags

  root :to => 'articles#index'
  ActiveAdmin.routes(self)

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
    validates_presence_of :email
    mount_uploader :image, ImageUploader
    has_many :authorizations
    has_many :userarticles
    has_many :articles, through: :userarticles

    def self.new_with_session(params,session)
        if session["devise.user_attributes"]
            new(session["devise.user_attributes"],without_protection: true) do |user|
            user.attributes = params
            user.valid?
        end
        else
            super
        end
    end

    def self.from_omniauth(auth, current_user)
        authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
        if authorization.user.blank?
            user = current_user || User.where('email = ?', auth["info"]["email"]).first
        if user.blank?
            user = User.new
            user.password = Devise.friendly_token[0,10]
            user.name = auth.info.name
            user.email = auth.info.email
        if auth.provider == "twitter"
            user.save(:validate => false)
        else
            user.save
        end
        end
            authorization.username = auth.info.nickname
            authorization.user_id = user.id
            authorization.save
        end
            authorization.user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]


  # GET /users/1
  def show
      @articles = Article.all
      @comments = Comment.all
  end

  # GET /users/1/edit
  def edit
      @articles = Article.all
      @comments = Comment.all
  end

  def index
      @articles = Article.all
      @comments = Comment.all
    @users = User.all
  end

  # PATCH/PUT /users/1
  def update
      @articles = Article.all
      @comments = Comment.all
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end

    #implement strong parameters
    def user_params
      params.require(:user).permit(:name, :user, :about)
    end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account <br>

<% ['facebook', 'twitter', 'github'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider), class: provider.to_s %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="headpart"><h1>Editing user</h1></div>

<%= render 'form' %>
<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<div class="headpart"><h2>Listing users</h2></div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="headpart">
    <% if user_signed_in? && current_user.email == @user.email %>
        <h2>displaying your profile <span><%= link_to 'Edit', edit_user_path(@user) %></span></h2>
        <% else %>
        <h2><%= @user.email.split('@')[0] %>'s profile</h2>
    <% end %>

</div>

<p>
  <strong>Username:</strong>
    <% if @user.name == nil %>
        No chosen Username
    <% else %>
    <%= @user.name %>
    <% end %>
</p>

<p><strong>About:</strong>
    <% if @user.about == nil %>
        No about information
    <% else %>
    <%= @user.about %>
    <% end %>
</p>




<div class="section-container">
    <div class="profile-started">
        <h2>games started</h2>
        <% @articles.each do |article| %>
            <% if article.player_names == @user.email %>
            <p><%= link_to article.title, article_path(article), 'data-no-turbolink' => true %></p>
            <% end  %>
        <% end  %>
    </div>

    <div class="profile-started">
        <h2>Games Joined</h2>
        <% @articles.each do |art| %>
            <% limit = 0 %>
            <% if art.users.exists?(:email => @user.email) %>
                <p><%= link_to art.title, article_path(art), 'data-no-turbolink' => true %></p>
                <% limit += 1 %>
                <% break if limit == 5 %>
            <% end %>
        <% end %>
    </div>

    <div class="profile-started">
        <h2>Comments</h2>
        <% @comments.where(:author_name => @user.email).each do |art| %>
        <p>
            <%= link_to art.body, article_path(art.article_id), 'data-no-turbolink' => true %>
        </p>
        <% end %>
    </div>
</div>