config/routes.rb
NautsRails::Application.routes.draw do

    devise_for :admin_users, ActiveAdmin::Devise.config

    get "pages/terms"
    get "pages/welcome"
    get "pages/landing"
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
    resources :users
    resources :articles do
        resources :comments
    end
      resources :tags

  root :to => 'articles#index'
  ActiveAdmin.routes(self)

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :articles, through: :taggings


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
        @tags = Tag.all
    end

    def show
        @articles = Article.all
        @comments = Comment.all
        @tag = Tag.find(params[:id])
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<div class="view-holder">
    <div class="now-viewing view">
        Now displaying
    </div>

    <div class="dropdown view">
        <% if current_page? ('/tags/1') %>
        <span>Basketball</span>
        <% elsif current_page? ('/tags/2') %>
        <span>Football</span>
        <% elsif current_page? ('/tags/3') %>
        <span>Soccer</span>
        <% elsif current_page? ('/tags/4') %>
        <span>Baseball</span>
        <% elsif current_page? ('/') %>
        <span>All Sports</span>
        <% else %>
        <span> <%= @tag.name %><span>
        <% end %>

        <div class="dropdown-content">
            <p><a href="../">all sports</a></p>
            <p><a href="../tags/1">basketball</a></p>
            <p><a href="../tags/2">football</a></p>
            <p><a href="../tags/3">soccer</a></p>
            <p><a href="../tags/4">baseball</a></p>
        </div>
    </div>
    <div class="end-viewing view">
        games
    </div>
</div>

<div class="rightsign">
    <% if user_signed_in? %>
    <p class="right-user">
        <%= link_to current_user.email.split('@')[0], current_user %> <span class="loggerout"><%= link_to "Logout", destroy_user_session_path %></span>
    </p>
    <%= link_to "Start A Sports Game", new_article_path, class: "new_article" %>
    <% else %>
    <p class="right-user"><%= link_to "Login", new_user_session_path %></p>
    <%= link_to 'login to start a game', '/users/sign_in', method: :get, class: "new_article" %>
    <% end %>
</div>

<div class="gmapper">
  <div id="map" style=' height: 400px;'></div>
</div>

<div id= "articles-holder">
  <% @tag.articles.each do |article| %>
  <div class="all_articles">
      <div class="general-data">
          <h2 class="art-title"><%= link_to article.title.length >= 20 ? article.title.first(20) + "..." : article.title, article_path(article), 'data-no-turbolink' => true %></h2>
          <p> Setting: <%= article.setting %> <br>
           Location: <%= article.location %></p>
          <p class="joined_body"><%= article.body.length >= 60 ? article.body.first(60) + "..." : article.body  %></p>
      </div>
      <div class="game-date">
          <p class="month"><%= article.month.to_s.first(3) %></p>
          <h2 class="day"><%= article.day.to_i.floor %></h2>
          <p class="time"><%=  article.time %></p>
      </div>
      <div class="players"></div>
          <p class="joined_players"><%= article.player_names.length %> spots filled: <%= article.players%> left </p>
          <p class = "postedby">posted by: </span>
          <% if article.users.length >= 1 %>
              <a href='/users/<%=article.users.first.id %>'><span class=posted> <%= article.users.first.email.split('@')[0] %> </span></a>
          <% end %>
      </p>
  </div>
  <% end %>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    var markers = handler.addMarkers([
        <% @tag.articles.each do |article| %>
            { lat: <%= article.latitude %>, lng: <%= article.longitude %>},
        <% end %>
    ]);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();

});
</script>